cluster:
  name: ${CLUSTER_NAME}
  routing:
    allocation:
      awareness:
        attributes: zone
        force:
          zone:
            values: zone0,zone1,zone2

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

cloud:
  azure:
    storage:
      account: ${AZURE_STORAGE_ACCOUNT}
      key: ${AZURE_STORAGE_KEY}

repositories.azure:
  container: elasticsearch
  compress: true

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}


script.inline: true
action.auto_create_index: false